# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1cf73db1fdcf91942d16c0ee0d4f393edc8c1c7ca482e6ddfc5161a09e12f0b68d8cd0cd49d2078b144af7492a6649c34a4591fb577e73c7cc67fc6ef6722c6

test:
  secret_key_base: f82cdb872b29ec4627e442c3eb5d03ba67b318f219291af9986c441b1af32dbeb82c36215e97c68f4663a663e53e13250f90a97bd3f89fb336c8496d328de284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
